#!/usr/bin/awk -f
# covariance
{
    if(NF>1){ a=$1; b=$2 }else{ a=NR; b=$1 }
    sum_a=sum_a+a
    sum_b=sum_b+b
    sum_prod=sum_prod+(a*b)
    # } END { <- to only print the final STDEV
    # difference between mean of products and product of means
    print ((sum_prod/NR) - ((sum_a/NR) * (sum_b/NR)))
}
