#!/usr/bin/awk -f
{
    sum_a=sum_a+$1
    sum_b=sum_b+$2
    sum_prod=sum_prod+($1*$2)
    # } END { <- to only print the final STDEV
    # difference between mean of products and product of means
    print ((sum_prod/NR) - ((sum_a/NR) * (sum_b/NR)))
}
