#!/usr/bin/gawk -f
#
# print the column with the largest difference in distribution from the last column
#
function print_array(array){
    for(i in array) printf "%s:%s ", i, array[i]
    printf "\n"    
}

function abs(x){ if(x < 0) return (0 - x); else return x;}

# return a scalar metric of the difference in two distributions
function difference_in_distributions(as, bs){
    difference=0
    for(k in as) difference += abs(as[k] - bs[k])
    return (difference / length(as))
}

{
    for (i=1; i<=NF; i++){
        if(i == NF){
            ys[NR]=$i;
            y_groups[$i]++;
        } else {
            xs[i][NR]=$i;
        }
    }
}

function best_attribute(xs, ys){
    for (g in ys) y_groups[ys[g]]=0;
    for (g in ys) y_groups[ys[g]]++;

    diff=0
    col=0
    for(i=1; i<=length(xs); i++){
        for (g in xs[i]) groups[xs[i][g]]=0;
        for (g in xs[i]) groups[xs[i][g]]++;
        my_diff = difference_in_distributions(groups, y_groups);
        if(my_diff > diff){ diff=my_diff; col=i; }
    }
    return col
}

END{
    print best_attribute(xs, ys)
}
