#!/usr/bin/gawk -f
# Gaussian Blur -- optional first argument specifies the radius of the blur.
function normal(x){ return (exp(-0.5 * (x*x)) / sqrt(6.2831853)); }
function add(value,place){
    for(j=-radius; j<=radius; j++){ blurred[(place + j)] += (value*kernel[j]) }
}

BEGIN {
    if(ARGV[1] ~ /[0-9.]/){
        radius = ARGV[1]; ARGV[1] = "-";
    }else{
        radius = 3;
    }
    for(r=-radius; r<=radius; r++){ kernel[r] = normal(r); }
}

{
    add($1, NR);
    print blurred[NR-radius];
}

END { for(i=(1 - radius);i<=radius;i++){ print blurred[NR+i] } }
