#!/usr/bin/gawk -f
# Harmonic Mean
# reciprocal of the arithmetic mean of the reciprocals
{
    for (i=1; i<=NF; i++)
    {
        if($i ~ /[0-9.]/){sum[i] += 1/$i; count[i]++}
        if(i == 1){ line = count[i]/sum[i] }
        else{       line = line " " count[i]/sum[i]}
    }
    print line
}
