#!/usr/bin/gawk -f
# Kolmogorov-Smirnov test for samples from at least two distributions
function abs(x){ if(x < 0) return (0 - x); else return x; }
function max(x,y){ if(x > y) return x; else return y; }
BEGIN{ largest_diff[1] = 0; }
{
    for (i=1; i<=max(NF, length(largest_diff)); i++){
        if($i ~ /[0-9.]/) cumulative[i] += $i;
        diff = abs(cumulative[i] - cumulative[1]);
        if(diff > largest_diff[i]) largest_diff[i] = diff;
        if(i == 1){ line = largest_diff[i] }else{ line = line " " largest_diff[i]}
    }
    print line
}
