#!/usr/bin/awk -f
# running minimum
{
    for (i=1; i<=NF; i++)
    {
        if((min[i] == "") || ($i < min[i])){ min[i] = $i}
        if(i == 1){ line = min[i] }else{ line = line " " min[i]}
    }
    print line
}
