#!/usr/bin/awk -f
{
    if(NF>1){ a=$1; b=$2 }else{ a=NR; b=$1 }
    sum_x=sum_x+a
    sum_y=sum_y+b
    sum_square_x=sum_square_x+(a*a)
    sum_prod=sum_prod+(a*b)
    # } END { <- to only print the final STDEV
    # difference between mean of products and product of means
    var_x = (sum_square_x/NR) - ((sum_x/NR) * (sum_x/NR))
    cov = ((sum_prod/NR) - ((sum_x/NR) * (sum_y/NR)))
    if(var_x == 0) beta=0;else beta=(cov / var_x);
    alpha = (sum_y/NR) - (beta * (sum_x/NR))
    if(alpha < 0)
        print "y = " beta "x - " (0 - alpha)
    else
        print "y = " beta "x + " alpha
}
