#!/usr/bin/awk -f
# standard deviation
{
    for (i=1; i<=NF; i++)
    {
        sum[i] += $i;
        sum_of_squares[i] += $i * $i;
        printf "%f ", sqrt(sum_of_squares[i]/NR - (sum[i]/NR)**2);
    }
    printf "\n"
}
