#!/usr/bin/Rscript --vanilla
# -*- R -*-
# 
# T test for samples from two distributions (columns)
d <- read.table("stdin", header=FALSE, as.is=TRUE, fill=TRUE);
x <- as.vector(d[1]); col1 <- x[!is.na(x)];
y <- as.vector(d[2]); col2 <- y[!is.na(y)];

t.test(col1,col2)
